### ISSUE TITLE
Production - LDRS 420

### ISSUE THREAD

**Issue by MaraChequer** [TWUOnline/bug-tracking#686] opened 2023-02-03 19:42 UTC
### Instructions
- [x] Ready to create Bookdown

Please upload required files as attachments.

**Comment by kmarjanovic** [comment] 2023-11-15 18:22
@MaraChequer checking on this issue and reassigning to Production.

**Comment by meher-ahmed** [comment] 2023-11-16 23:53
Hi Mara letme if you would want this course to be transferred to a new Moodle shell and if so which location.

**Comment by MaraChequer** [comment] 2023-11-21 01:13
Hi Meher, I just created a new Moodle shell for the course https://learn.twu.ca/course/view.php?id=32158, Please let me know if you can transfer all to it, or if you need me to prepare the layout and format to fir the other BALead 6week masters (I.e: https://learn.twu.ca/course/view.php?id=28276&section=0#tabs-tree-start) or if  you would only add the bookdown to the -Course Units- tab?
Thank you in advance!

**Comment by chloecwh** [comment] 2023-12-18 17:57
@MaraChequer Commenting here to see if you still want this course to be produced

**Comment by kmarjanovic** [comment] 2023-12-22 19:08
@chloecwh this is a BA Lead course - all of which need to be converted to bookdown.  GX is still a priority, then the [Innovation courses](https://www.notion.so/twuid/Innovation-Certificates-458a9933492f437b8d1eae475932bc65), but BA Lead will likely be needed by May (a guess, as nothing's been confirmed).

**Comment by chloecwh** [comment] 2023-12-22 19:11
@kmarjanovic sounds good

**Comment by MaraChequer** [comment] 2024-03-22 21:48
@meher-ahmed, 
I've made changes to Units 1-8 in [your LDRS 420 files](https://mytwu.sharepoint.com/sites/LearningDesign/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FLearningDesign%2FShared%20Documents%2FBA%2DLead%20Courses%20%2D%20Doc%2FLDRS420%2FLDRS%20420%20Ba%2DLead&viewid=40cf7fb5%2D2131%2D4adc%2Dbd1e%2D88296482bfbb&sw=auth). However, I noticed that Units 9 and 10 are missing. There's no urgency on this matter, but please let me know when you have the files in the folder. Thank you!

**Comment by chloecwh** [comment] 2024-04-24 17:54
@meher-ahmed following up on units 9 and 10.

**Comment by kmarjanovic** [comment] 2024-04-29 17:21
@chloecwh this course will be starting a course revision in the next week or so.  I've moved it up in priority from SP 2025 to FA 2024 as we have SME & ID availability.  Please let @MaraChequer know if you need anything to complete the bookdown.

If Production needs to wait until the template is decided, Mara you can use the old  FAR version to discuss with Steven.

Thanks all!

**Comment by MaraChequer** [comment] 2024-05-01 05:05
[heart]         Mara Chequer reacted to your message:
________________________________

**Comment by meher-ahmed** [comment] 2024-05-03 20:41
Hi @MaraChequer i have made all the changes mentioned in the comment section for LDRS 420 from U1-U8. Can you please add U9 and U10 in this [sharepoint link](https://mytwu.sharepoint.com/sites/LearningDesign/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FLearningDesign%2FShared%20Documents%2FBA%2DLead%20Courses%20%2D%20Doc%2FLDRS420%2FLDRS%20420%20Ba%2DLead&viewid=40cf7fb5%2D2131%2D4adc%2Dbd1e%2D88296482bfbb) and I'll add the new content?

**Comment by chloecwh** [comment] 2024-05-03 20:45
Hi @meher-ahmed have you migrated unit 9 and 10 from [Grav](https://learn.twu.ca/course/view.php?id=23573&section=10#tabs-tree-start) to bookdown?

**Comment by meher-ahmed** [comment] 2024-05-03 21:57
> Hi @meher-ahmed have you migrated unit 9 and 10 from [Grav](https://learn.twu.ca/course/view.php?id=23573&section=10#tabs-tree-start) to bookdown?

No @chloecwh would it possible to get the content in word? and I can create new .rmd files for U9 and U10 and add it to LDRS 420?

**Comment by chloecwh** [comment] 2024-05-03 22:05
@meher-ahmed  Since the content is in GRAV, we are responsible to bring the content over to Bookdown and share a word file to ID for revision. Same as the last 8 units.

**Comment by meher-ahmed** [comment] 2024-05-10 22:46
Hi @chloecwh U9 and U10 has been added to the bookdown. Can you please review it and let me know? Thank you.

**Comment by chloecwh** [comment] 2024-05-13 20:29
Thank you @meher-ahmed

**Comment by chloecwh** [comment] 2024-05-13 22:08
@MaraChequer Here are the docs. I've also uploaded to Sharepoint. Thanks for being patience! 
[Unit_9_LDRS420.docx](https://github.com/TWUOnline/bug-tracking/files/15300430/Unit_9_LDRS420.docx)
[Unit_10_LDRS420.docx](https://github.com/TWUOnline/bug-tracking/files/15300432/Unit_10_LDRS420.docx)

**Comment by MaraChequer** [comment] 2024-05-15 03:32
thank you very much @chloecwh :)

**Comment by MaraChequer** [comment] 2024-05-22 03:14
Hello @chloecwh, LDRs 420 course content for the book is ready for production, ID and SME have revised. Thank you!

**Closed** 2024-09-04 16:46 UTC
Labels: Production
