### ISSUE TITLE
LDRS 667 edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#614] opened 2022-08-25 05:25 UTC
### Course
LDRS 667
### URL
[LDRS 667 OL - Practicum (FA 2022)](https://learn.twu.ca/course/view.php?id=24340)
### Instructions
(sent in email Aug 23)

Please change the following: 

1.  Course introduction tab-Assessment Summary-% values are incorrect
    (<https://learn.twu.ca/course/view.php?id=24340>)

2.  Prework tab-Activity checklist-Activity 0.2 (in blue box) *If you need a
    refresher on how to write Learning Outcomes for your Practicum, read: Queens
    University Center for Teaching and Learning. (n.d.)* [“Learning outcomes;
    course/curriculum
    design.”](http://www.queensu.ca/ctl/teaching-support/course-and-program-design)-link
    broken and needs to be replaced with current link
    (<https://learn.twu.ca/course/view.php?id=24340&section=3#tabs-tree-start>)  
    **Optional: Screenshots**  
    

    ![ldrs 667ol change 1](media/295f55e1fc1a5e213c2451997f24117b.jpg)

    ![ldrs 667ol change 2](media/38e1751a40a422dd700593380aaa9f9e.jpg)

Corrections:

1.  Course introduction tab-Assessment Summary-% values are supposed to match
    the values as listed in the Assignments\>overview tab (screenshot attached).

|   |
|---|

    >   **Practicum Proposal** 

    10% 

|                                                        | 5%   |   |
|--------------------------------------------------------|------|---|
|                                                        | 5%   |   |
|                                                        | 5%   |   |
|                                                        | 5%   |   |
| **Lesson Plan 1**                                      | 10%  |   |
| **Lesson Plan 2**                                      | 10%  |   |
| **Lesson Plan 3**                                      | 10%  |   |
| **Reflective Practice Learning Activities: 8, 9, 10**  | 24%  |   |
| **Reflective Practice Practicum Portfolio **           | 16%  |   |

>   **Reflective Practice Comment 1** 

>   **Reflective Practice Comment 2** 

>   **Reflective Practice Comment 3** 

>   **Reflective Practice Comment 4** 

1.  Prework tab-Activity checklist-Activity 0.2 (in blue box)  correct link
    is* *<https://www.queensu.ca/ctl/resources/course-design>

**Comment by kmarjanovic** [comment] 2022-08-25 05:26
Sorry - tried to copy/pasta from email, so formatting is wonky.  @MeeksonHundoo let me know if you have any questions.
Thanks!!

**Comment by MeeksonHundoo** [comment] 2022-08-26 05:27
Hello @kmarjanovic this has been done! This is a dupe of bug number #607 https://github.com/TWUOnline/bug-tracking/issues/607

**Closed by MeeksonHundoo** 2022-08-26 05:27 UTC
Labels: Production
